### ISSUE TITLE
Update AO instance list

### ISSUE THREAD

**Issue by privacytime101** [benbusby/farside#112]
Hi, I was checking out this project when I noticed AnonymousOverflow's instance list was outdated. 
It'd be great if this could be updated, especially since a bad actor was removed from the list since then. Thanks!

**Comment by benbusby** [comment]
@privacytime101 thanks for the heads up!

Would you all be open to providing an easily machine readable version of the available instances? Currently Farside auto-updates instance lists in the [nightly CI build](https://github.com/benbusby/farside/blob/main/.github/workflows/update-instances.yml) for services that provide instances via json or otherwise. Happy to open an issue over there too if you want, just wanted to gauge interest/feasibility first.
