### ISSUE TITLE
Re-evaluate Nitter redirects

### ISSUE THREAD

**Issue by http403** [benbusby/farside#113]
As of writing, only `nitter.1d4.us` appered working. Rest two are not. `nitter.42l.fr` soft shutoff due to the recent paywall, and `twitter.076.ne.jp` redirects to `twitter.076.moe` which had the server taken down as the DNS record is missing.

**Comment by benbusby** [comment]
I'm going to hold off on modifying the Nitter instance list until it's clear whether or not the project is actually going to stick around. From a quick glance, it looks like all of the instances are failing to fetch user content (but aren't returning an error code, which is annoying).

**Comment by benbusby** [comment]
Looks like the Nitter team figured a way around the recent Twitter changes, but it might take a while for the instances to update to the latest version. I'm going to close this since it looks like some are coming back online already, but will revisit if there's a significant delay in the instances getting updated.
