### ISSUE TITLE
Add Farside to Fdroid

### ISSUE THREAD

**Issue by Cwpute** [benbusby/farside#120]
Would it be possible to add Farside to the Fdroid repository ?

Currently, the only efficient redirector that links to opensource frontends or alternatives is [https://framagit.org/tom79/nitterizeme](UntrackMe), which hasn't been updated in a year, so there is a lack of a good app for this.
Listing Farside on Fdroid would help make this solution better known to the public, and attract possible contributions to further strenghten the project.

**Comment by benbusby** [comment]
I'm not really sure how that would work since Farside isn't really an "app", it's just a web service. It seems like the better option would just be to use farside links in an app like the one you mentioned (i.e. `farside.link/nitter` instead of `nitter.net`), or use a Firefox extension that can handle URL rewriting on each page.

**Comment by Cwpute** [comment]
Oh sorry, i guess i didn't understand properly how Farside worked. Since it's called a redirector, i assumed it was an app, but it isn't.
So how i understand now is, it does the instance selection by itself when you use the links then, but you'd need to have a separate tool to do the automatic redirection by itself…

Too bad, because what i'm searching for is the automated tool more than the instance links :/ but i'll keep Farside in the back wf my brain for later !

No i don't have Firefox installed on my Android, as i find it too bloated for a browser on smartphone. I'll keep searching for a good alternative, or eventually build mine, who knows 🤷

Thanks!
