### ISSUE TITLE
Docker on the docket?

### ISSUE THREAD

**Issue by 0x646a73** [benbusby/farside#122]
Any plans to containerize with Docker?

**Comment by 0x646a73** [comment]
Seems like a nay.

**Comment by alkaris2** [comment]
Just read the documentation on how to create Docker container from https://www.docker.com on how to create and setting up a Docker container for your application. There's nothing special required just to setup a Docker container because all it is, is a virtualized system container environment for running applications on with network access.

**Comment by 0x646a73** [comment]
Right, but that does require spending meaningful time auditing the code to understand all the required (and optional) volume mount points for config and data. files I only asked because the owner provided Docker files for another of his projects (whoogle-search). Issue closed.
