### ISSUE TITLE
Feature suggestion: Choose frontend automatically for link

### ISSUE THREAD

**Issue by 6k27f** [benbusby/farside#37]
It would be really cool if users could, without entering the frontend name, be automatically redirected to an appropriate frontend service for a given link. For example, if https://farside.link/https://www.youtube.com/watch?v=whatever redirected to [an Invidious instance]/watch?v=whatever

**Comment by m040601** [comment]
>  ... with a 1:1 mirroring of URL paths with their parent service...

This is just such a great improvement. Really makes configuring your Firefox, your text mode browser, your router, your network etc. such a piece of cake.

A big thanks to benbusy for his work on this wonderfull, so much underrated, tool.
Should be much much better known.

**Comment by benbusby** [comment]
Thanks, I appreciate the kind words!

**Comment by lhindir** [comment]
Could you make this work with the `_`feature as well (e.g. https://farside.link/_/https://www.youtube.com/watch?v=dQw4w9WgXcQ)? On an unrelated note, the `_` feature doesn’t seem to work reliably for me. It frequently drops the path or query string so I end up at e.g. https://piped.kavin.rocks/watch (without the `v` parameter) or https://libredd.it (without the search path I input).

**Comment by benbusby** [comment]
@lhindir thanks for pointing that out, should be fixed now.

**Comment by lhindir** [comment]
Thanks! Another thing: The Bibliogram dev chose to use a different path layout than Instagram. Mainly, users have a leading `/u/` not present in Instagram URL’s, “so all existing top level paths are a feature page, and all URLs starting with /u/ are users.”[^1] I don’t know whether you think it’s in scope for Farside to handle these path quirks in downstream services, but right now, using most Instagram links with this feature fails because of this.

[^1]: https://git.sr.ht/~cadence/bibliogram-docs/tree/master/item/docs/Reserved%20URLs.md

**Comment by benbusby** [comment]
Yeah I've encountered that as well. I'd rather not get in the habit of handling path inconsistencies like that in Farside, but since there isn't a suitable alternative to Bibliogram that does match Instagram's path paradigm, it might be necessary. I'll consider adding that.

**Comment by benbusby** [comment]
@lhindir I just pushed an update to prepend the `/u/` prefix if determined to be a link for a specific user's profile page.
