### ISSUE TITLE
Ditch Github

### ISSUE THREAD

**Issue by pedrolucasp** [benbusby/farside#44]
I believe it's rather ironic for a tool that provides privacy-oriented/ethical frontend alternatives 
to various services to host itself on Github. It should at a bare minimum be an archived 
repository pointing to the hosted version somewhere else. You can pick from using a 
self-hosted version of Gitlab, Gitea, gogs, cgit, stagit, git-web, sourcehut, you name it.

**Comment by benbusby** [comment]
Figured I'd give an update on this here, in case anyone comes across it.

Since Farside depends heavily on scheduled builds to update the list of available services per instance, migration to Sourcehut depends on the completion of https://todo.sr.ht/~sircmpwn/dispatch.sr.ht/23. As soon as nightly builds are possible, it should be a fairly easy migration.
