### ISSUE TITLE
Farside seems to be pinging repeatedly on the same second

### ISSUE THREAD

**Issue by austinhuang0131** [benbusby/farside#60]
![Screen Shot 2022-08-13 at 17 28 43](https://user-images.githubusercontent.com/16656689/184511323-49077fe5-c808-4106-8e57-5174fc73810d.png)

You could ratelimit the instance...

**Comment by benbusby** [comment]
Is this happening constantly or just during that one time on Aug 12? My guess is that this has to do with #54, since there have been a ton of issues with that PR's re-implementation of the scheduler, where it queries the same instance multiple times in under a second. From a quick look at the real farside.link server, it doesn't seem to be sending those requests.

**Comment by austinhuang0131** [comment]
I suppose...
