### ISSUE TITLE
Suggestion: implement redirect preserving Farside in browser history

### ISSUE THREAD

**Issue by ltGuillaume** [benbusby/farside#7]
Oftentimes services like Bibliogram are locked out by the original service because of excessive traffic from a single IP. Farside could help more in this case if you could easily retry with another service. A suggestion would be to have the (e.g.) https://farside.link/service/... link in the browser history, so that if you get an error with the first instance you get redirected to, simply pressing the Back-button will bring you back to Farside and another instance is tried immediately.

I don't have any experience with Elixir, but perhaps something client-side using either HTML `<meta http-equiv="refresh" content="0; url=https://example.com/">` or JavaScript `history.pushState()` would do the trick.

The browser would then also be prevented from caching the request (or local JavaScript should redo the instance request to the server), otherwise you'd get the same instance.

**Comment by benbusby** [comment]
Well the main goal of Farside is to ensure that any instance that the user is forwarded to is working beforehand, which is why the instances are checked every 5 mins for availability/successful results. 

That being said, I do agree that being able to navigate back and go to a new instance would be useful, especially in the case where an instance goes down between updates. I'll try to get to that soon.

**Comment by ltGuillaume** [comment]
> ...to ensure that any instance that the user is forwarded to is working beforehand...
That would obviously be best, but it doesn't seem to work reliably for Bibliogram instances.

So yeah, thanks for looking into this, would be a great addition!

**Comment by Albonycal** [comment]
> That would obviously be best, but it doesn't seem to work reliably for Bibliogram instances.

Yea

**Comment by benbusby** [comment]
So I've looked into this a little bit more, and am unsure about the best way to move forward.

The `http-equiv="refresh" ...` approach doesn't actually seem to preserve the page (at least not from what I noticed in my testing), and I'd rather not come up with a Javascript solution since it would break functionality for anyone who has Javascript blocked by default. 

My thought is to either A) investigate why Bibliogram instances seem particularly prone to being limited, and figure out if there's a better way to treat these instances within Farside, or B) proxy the connection to individual instances through Farside, and fetch a new instance if the user refreshes while viewing an instance through the Farside proxy. 

I'm personally leaning more towards A, but I'm not sure how much special treatment should be given to individual services like that. I could increase the frequency with which instance lists are queried for availability, but that puts a little bit of additional stress on instances (although tbh querying for one page per instance isn't anything excessive).  

That being said, if I've overlooked something with the client side redirecting approach, please let me know. I have a working example of the `http-equiv` redirect, but like I said, it doesn't seem to actually be pushed into browser history. I did find [this bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=113556) supporting this finding, but it's 20 years old now and could be out of date.

**Comment by ltGuillaume** [comment]
You're right, even with a non-zero timeout. It's not like that in the specs AFAIK, but apparently browser do have it implemented like that: no history preservation.

I agree that proxying would be the last result. 

I see more and more bibliogram instances that put on their own restriction for end users via quota (see e.g. "Quota left: 24" at the lower left of the page), which is something farside wouldn't be able to handle server-side anyway (it's based on the end user's IP when making the request to the instance), so it would still be great to have this. Perhaps an optional URL parameter or something like farside.link/bibliogram/r/user/xxx (adding /r/ for redirect), which _would_ use JavaScript to redirect, could be an action?

**Comment by benbusby** [comment]
That's a great idea. I just implemented that approach and opened a PR, let me know your thoughts and I'll merge!

**Comment by ltGuillaume** [comment]
Apart from the HTML/JavaScript, I can't really read the code, but if it works as advertised, I think it sure looks like an elegant solution 😃

**Comment by ltGuillaume** [comment]
Ooh just one thing,  /r/ is also used by Reddit, of course, so is would it become farside.link/r/teddit/r/topic now, or farside.link/teddit/r/r/topic? Obviously the first would be better.

**Comment by benbusby** [comment]
It would be the first one -- the URL format for preserving history would be `farside.link/r/<service>/<path>`.

That being said, I guess it still is a little bit confusing, but I'm not sure of any better solution. I think I'll go ahead and merge for now, and can always change it later if anyone finds the path prefix to cause confusion.

**Comment by ltGuillaume** [comment]
Agreed! `/_/` is also easier to spot in the URL.

I think it's a nice option, primarily because it's not necessary for _every_ service that's supported. This implementation allows the user to cherry-pick.
