### ISSUE TITLE
Browser extension

### ISSUE THREAD

**Issue by S7venLights** [benbusby/farside#73]
Would a autoredirect browser extension be possible?
I found this: https://addons.mozilla.org/en-US/firefox/addon/farside/

and 
https://addons.mozilla.org/en-US/firefox/addon/privacy-redirect/

and this is relevant: https://github.com/SimonBrazell/privacy-redirect/issues/329

**Comment by benbusby** [comment]
There are instructions on how to integrate Farside into a redirector browser extension in the wiki: https://github.com/benbusby/farside/wiki/Browser-Extension

I think it's preferable to use an existing browser extension like the one documented in the wiki, rather than having a specific extension just for Farside.

**Comment by S7venLights** [comment]
Thanks
