### ISSUE TITLE
teddit.manasiwibi.com has issues

### ISSUE THREAD

**Issue by testman42** [benbusby/farside#88]
It returns various kinds of errors instead of displaying subreddits or posts.

Please remove.

Aditionally, consider implementing a system for community to suggest instance additions and removals.

At least I think that instance suggestions should be separate from other technical issues.

Or maybe just an "instance suggestion" issue abel for start.

**Comment by benbusby** [comment]
Apologies for the delay. Farside's Teddit instances are automatically pulled from the list of public instances that Teddit supplies from here: https://codeberg.org/teddit/teddit/raw/branch/main/instances.json. I'd rather not get in the habit of manually singling out specific instances that don't work, but will consider it if this continues to be a problem. In this case, it'd be preferable if the instance with the error also just returned an error status code, since Farside will ignore instances that don't return a success code. 

Alternatively Farside could be updated to look for more than just a success status code from the instance. It could use a per-service check to make sure that the data on the page matches an expected format or something, but that'd obviously make the scheduled updates slower.

In the meantime I've added a label for future issues related to this sort of thing.

**Comment by benbusby** [comment]
The instance in question seems to have been removed as of https://codeberg.org/teddit/teddit/commit/a02025a86fa80dafe9b9adfda5f52460618ab925, so I'm going to close this issue.
